@Insurance_WOM
Feature:oneShotDelivery


  @ejecucionUnitariasSP
  Scenario Outline: prueba srv40229-1-0 pruebas unitarias (sinPromocion)


    Given header 'Content-Type' = 'application/json'
    When url 'http://ott.wom.uat/ocp/customer/srv40229-1-0/rest/productOrdering/productOrderOneShotDelivery'

    And request { "ProductOrderOneShotDeliveryRequestMessage": {"<orderIdDOM>": "<orderId>","<cardId>": "<tarjeta>","<email>": "<e-mail>","<channel>": "<canales>","items":[{"<itemCode>": "<codigoItem>","<itemName>": "<nombreP>","<itemType>": "<tipoProducto>","<type>": "<PrePOST>","<serviceType>":"<producto>","<quantity>": <cantidad>,"installmentInfoMsg": {"<version>": "<versionPago>","<noOfInstallments>": "<cuotas>"}}]}}
    And method POST
    * configure connectTimeout = 120000
    * configure readTimeout = 120000
    Then assert responseStatus == 400 || responseStatus == 401 || responseStatus == 402 || responseStatus == 404 || responseStatus == 409 || responseStatus == 501

    Examples:
      | orderIdDOM | orderId        | cardId | tarjeta                  | email | e-mail                          | channel | canales | itemCode | codigoItem    | itemName | nombreP    | itemType | tipoProducto | type | PrePOST        | serviceType | producto | quantity | cantidad | version | versionPago | noOfInstallments | cuotas |
      | orderIdDOM |                | cardId | 617094119c321f00012933a4 | email | jeremy.aldea@consultores.wom.cl | channel | MIWOM   | itemCode | 001.004.0003  | itemName | WOM STB pn | itemType | HardwareOP   | type | Postpaid       | serviceType | PRODUCT  | quantity | 1        | version | Fibra3      | noOfInstallments | 3      |
      | orderIdDOM | asdasdasdasdsa | cardId | 617094119c321f00012933a4 | email | jeremy.aldea@consultores.wom.cl | channel | MIWOM   | itemCode | 001.004.0003  | itemName | WOM STB pn | itemType | HardwareOP   | type | Postpaid       | serviceType | PRODUCT  | quantity | 1        | version | Fibra3      | noOfInstallments | 3      |
      |            |                | cardId | 617094119c321f00012933a4 | email | jeremy.aldea@consultores.wom.cl | channel | MIWOM   | itemCode | 001.004.0003  | itemName | WOM STB pn | itemType | HardwareOP   | type | Postpaid       | serviceType | PRODUCT  | quantity | 1        | version | Fibra3      | noOfInstallments | 3      |
      | orderIdDOM | null           | cardId | 617094119c321f00012933a4 | email | jeremy.aldea@consultores.wom.cl | channel | MIWOM   | itemCode | 001.004.0003  | itemName | WOM STB pn | itemType | HardwareOP   | type | Postpaid       | serviceType | PRODUCT  | quantity | 1        | version | Fibra3      | noOfInstallments | 3      |
      | orderIdDOM | 5MC08KV6Z86IH   | cardId |                          | email | jeremy.aldea@consultores.wom.cl | channel | MIWOM   | itemCode | 001.004.0003  | itemName | WOM STB pn | itemType | HardwareOP   | type | Postpaid       | serviceType | PRODUCT  | quantity | 1        | version | Fibra3      | noOfInstallments | 3      |
      | orderIdDOM | 5MC08KV6Z86IH   | cardId | asdjasdn                 | email | jeremy.aldea@consultores.wom.cl | channel | MIWOM   | itemCode | 001.004.0003  | itemName | WOM STB pn | itemType | HardwareOP   | type | Postpaid       | serviceType | PRODUCT  | quantity | 1        | version | Fibra3      | noOfInstallments | 3      |
      | orderIdDOM | 5MC08KV6Z86IH   |        |                          | email | jeremy.aldea@consultores.wom.cl | channel | MIWOM   | itemCode | 001.004.0003  | itemName | WOM STB pn | itemType | HardwareOP   | type | Postpaid       | serviceType | PRODUCT  | quantity | 1        | version | Fibra3      | noOfInstallments | 3      |
      | orderIdDOM | 5MC08KV6Z86IH   | cardId | null                     | email | jeremy.aldea@consultores.wom.cl | channel | MIWOM   | itemCode | 001.004.0003  | itemName | WOM STB pn | itemType | HardwareOP   | type | Postpaid       | serviceType | PRODUCT  | quantity | 1        | version | Fibra3      | noOfInstallments | 3      |
      | orderIdDOM | 5MC08KV6Z86IH   | cardId | 617094119c321f00012933a4 | email |                                 | channel | MIWOM   | itemCode | 001.004.0003  | itemName | WOM STB pn | itemType | HardwareOP   | type | Postpaid       | serviceType | PRODUCT  | quantity | 1        | version | Fibra3      | noOfInstallments | 3      |
      | orderIdDOM | 5MC08KV6Z86IH   | cardId | 617094119c321f00012933a4 | email | asdasdj@gmail.com               | channel | MIWOM   | itemCode | 001.004.0003  | itemName | WOM STB pn | itemType | HardwareOP   | type | Postpaid       | serviceType | PRODUCT  | quantity | 1        | version | Fibra3      | noOfInstallments | 3      |
      | orderIdDOM | 5MC08KV6Z86IH   | cardId | 617094119c321f00012933a4 |       |                                 | channel | MIWOM   | itemCode | 001.004.0003  | itemName | WOM STB pn | itemType | HardwareOP   | type | Postpaid       | serviceType | PRODUCT  | quantity | 1        | version | Fibra3      | noOfInstallments | 3      |
      | orderIdDOM | 5MC08KV6Z86IH   | cardId | 617094119c321f00012933a4 | email | null                            | channel | MIWOM   | itemCode | 001.004.0003  | itemName | WOM STB pn | itemType | HardwareOP   | type | Postpaid       | serviceType | PRODUCT  | quantity | 1        | version | Fibra3      | noOfInstallments | 3      |
      | orderIdDOM | 5MC08KV6Z86IH   | cardId | 617094119c321f00012933a4 | email | jeremy.aldea@consultores.wom.cl | channel |         | itemCode | 001.004.0003  | itemName | WOM STB pn | itemType | HardwareOP   | type | Postpaid       | serviceType | PRODUCT  | quantity | 1        | version | Fibra3      | noOfInstallments | 3      |
      | orderIdDOM | 5MC08KV6Z86IH   | cardId | 617094119c321f00012933a4 | email | jeremy.aldea@consultores.wom.cl |         |         | itemCode | 001.004.0003  | itemName | WOM STB pn | itemType | HardwareOP   | type | Postpaid       | serviceType | PRODUCT  | quantity | 1        | version | Fibra3      | noOfInstallments | 3      |
      | orderIdDOM | 5MC08KV6Z86IH   | cardId | 617094119c321f00012933a4 | email | jeremy.aldea@consultores.wom.cl | channel | MIWOM   | itemCode |               | itemName | WOM STB pn | itemType | HardwareOP   | type | Postpaid       | serviceType | PRODUCT  | quantity | 1        | version | Fibra3      | noOfInstallments | 3      |
      | orderIdDOM | 5MC08KV6Z86IH   | cardId | 617094119c321f00012933a4 | email | jeremy.aldea@consultores.wom.cl | channel | MIWOM   | itemCode | 111.104.1233a | itemName | WOM STB pn | itemType | HardwareOP   | type | Postpaid       | serviceType | PRODUCT  | quantity | 1        | version | Fibra3      | noOfInstallments | 3      |
      | orderIdDOM | 5MC08KV6Z86IH   | cardId | 617094119c321f00012933a4 | email | jeremy.aldea@consultores.wom.cl | channel | MIWOM   |          |               | itemName | WOM STB pn | itemType | HardwareOP   | type | Postpaid       | serviceType | PRODUCT  | quantity | 1        | version | Fibra3      | noOfInstallments | 3      |
      | orderIdDOM | 5MC08KV6Z86IH   | cardId | 617094119c321f00012933a4 | email | jeremy.aldea@consultores.wom.cl | channel | MIWOM   | itemCode | null          | itemName | WOM STB pn | itemType | HardwareOP   | type | Postpaid       | serviceType | PRODUCT  | quantity | 1        | version | Fibra3      | noOfInstallments | 3      |
      | orderIdDOM | 5MC08KV6Z86IH   | cardId | 617094119c321f00012933a4 | email | jeremy.aldea@consultores.wom.cl | channel | MIWOM   | itemCode | 001.004.0003  | itemName |            | itemType | HardwareOP   | type | Postpaid       | serviceType | PRODUCT  | quantity | 1        | version | Fibra3      | noOfInstallments | 3      |
      | orderIdDOM | 5MC08KV6Z86IH   | cardId | 617094119c321f00012933a4 | email | jeremy.aldea@consultores.wom.cl | channel | MIWOM   | itemCode | 001.004.0003  |          |            | itemType | HardwareOP   | type | Postpaid       | serviceType | PRODUCT  | quantity | 1        | version | Fibra3      | noOfInstallments | 3      |
      | orderIdDOM | 5MC08KV6Z86IH   | cardId | 617094119c321f00012933a4 | email | jeremy.aldea@consultores.wom.cl | channel | MIWOM   | itemCode | 001.004.0003  |          |            | itemType | HardwareOP   | type | Postpaid       | serviceType | PRODUCT  | quantity | 1        | version | Fibra3      | noOfInstallments | 3      |
      | orderIdDOM | 5MC08KV6Z86IH   | cardId | 617094119c321f00012933a4 | email | jeremy.aldea@consultores.wom.cl | channel | MIWOM   | itemCode | 001.004.0003  |          |            | itemType | HardwareOP   | type | Postpaid       | serviceType | PRODUCT  | quantity | 1        | version | Fibra3      | noOfInstallments | 3      |
      | orderIdDOM | 5MC08KV6Z86IH   | cardId | 617094119c321f00012933a4 | email | jeremy.aldea@consultores.wom.cl | channel | MIWOM   | itemCode | 001.004.0003  | itemName | WOM STB pn | itemType |              | type | Postpaid       | serviceType | PRODUCT  | quantity | 1        | version | Fibra3      | noOfInstallments | 3      |
      | orderIdDOM | 5MC08KV6Z86IH   | cardId | 617094119c321f00012933a4 | email | jeremy.aldea@consultores.wom.cl | channel | MIWOM   | itemCode | 001.004.0003  | itemName | WOM STB pn | itemType | asdasda      | type | Postpaid       | serviceType | PRODUCT  | quantity | 1        | version | Fibra3      | noOfInstallments | 3      |
      | orderIdDOM | 5MC08KV6Z86IH   | cardId | 617094119c321f00012933a4 | email | jeremy.aldea@consultores.wom.cl | channel | MIWOM   | itemCode | 001.004.0003  | itemame  | WOM STB pn |          |              | type | Postpaid       | serviceType | PRODUCT  | quantity | 1        | version | Fibra3      | noOfInstallments | 3      |
      | orderIdDOM | 9YSD9KV88WV7H   | cardId | 617094119c321f00012933a4 | email | jeremy.aldea@consultores.wom.cl | channel | MIWOM   | itemCode | 001.004.0003  | itemName | WOM STB pn | itemType | null         | type | Postpaid       | serviceType | PRODUCT  | quantity | 1        | version | Fibra3      | noOfInstallments | 3      |
      | orderIdDOM | 9YSD9KV88WV7H   | cardId | 617094119c321f00012933a4 | email | jeremy.aldea@consultores.wom.cl | channel | MIWOM   | itemCode | 001.004.0003  | itemName | WOM STB pn | itemType | HardwareOP   | type |                | serviceType | PRODUCT  | quantity | 1        | version | Fibra3      | noOfInstallments | 3      |
      | orderIdDOM | 9YSD9KV88WV7H   | cardId | 617094119c321f00012933a4 | email | jeremy.aldea@consultores.wom.cl | channel | MIWOM   | itemCode | 001.004.0003  | itemName | WOM STB pn | itemType | HardwareOP   | type | Pasdasdostpaid | serviceType | PRODUCT  | quantity | 1        | version | Fibra3      | noOfInstallments | 3      |
      | orderIdDOM | 9YSD9KV88WV7H   | cardId | 617094119c321f00012933a4 | email | jeremy.aldea@consultores.wom.cl | channel | MIWOM   | itemCode | 001.004.0003  | itemName | WOM STB pn | itemType | HardwareOP   | type | a              | serviceType | PRODUCT  | quantity | 1        | version | Fibra3      | noOfInstallments | 3      |
      | orderIdDOM | 9YSD9KV88WV7H   | cardId | 617094119c321f00012933a4 | email | jeremy.aldea@consultores.wom.cl | channel | MIWOM   | itemCode | 001.004.0003  | itemName | WOM STB pn | itemType | HardwareOP   | type | null           | serviceType | PRODUCT  | quantity | 1        | version | Fibra3      | noOfInstallments | 3      |
      | orderIdDOM | 9YSD9KV88WV7H   | cardId | 617094119c321f00012933a4 | email | jeremy.aldea@consultores.wom.cl | channel | MIWOM   | itemCode | 001.004.0003  | itemName | WOM STB pn | itemType | HardwareOP   | type | Postpaid       | serviceType |          | quantity | 1        | version | Fibra3      | noOfInstallments | 3      |
      | orderIdDOM | 9YSD9KV88WV7H   | cardId | 617094119c321f00012933a4 | email | jeremy.aldea@consultores.wom.cl | channel | MIWOM   | itemCode | 001.004.0003  | itemName | WOM STB pn | itemType | HardwareOP   | type | Postpaid       | serviceType | asasda   | quantity | 1        | version | Fibra3      | noOfInstallments | 3      |
      | orderIdDOM | 9YSD9KV88WV7H   | cardId | 617094119c321f00012933a4 | email | jeremy.aldea@consultores.wom.cl | channel | MIWOM   | itemCode | 001.004.0003  | itemName | WOM STB pn | itemType | HardwareOP   | type | Postpaid       |             |          | quantity | 1        | version | Fibra3      | noOfInstallments | 3      |
      | orderIdDOM | 9YSD9KV88WV7H   | cardId | 617094119c321f00012933a4 | email | jeremy.aldea@consultores.wom.cl | channel | MIWOM   | itemCode | 001.004.0003  | itemName | WOM STB pn | itemType | HardwareOP   | type | Postpaid       | serviceType | null     | quantity | 1        | version | Fibra3      | noOfInstallments | 3      |
      | orderIdDOM | 9YSD9KV88WV7H   | cardId | 617094119c321f00012933a4 | email | jeremy.aldea@consultores.wom.cl | channel | MIWOM   | itemCode | 001.004.0003  | itemName | WOM STB pn | itemType | HardwareOP   | type | Postpaid       | serviceType | PRODUCT  | quantity |          | version | Fibra3      | noOfInstallments | 3      |
      | orderIdDOM | 9YSD9KV88WV7H   | cardId | 617094119c321f00012933a4 | email | jeremy.aldea@consultores.wom.cl | channel | MIWOM   | itemCode | 001.004.0003  | itemName | WOM STB pn | itemType | HardwareOP   | type | Postpaid       | serviceType | PRODUCT  | quantity | 1asd     | version | Fibra3      | noOfInstallments | 3      |
      | orderIdDOM | 9YSD9KV88WV7H   | cardId | 617094119c321f00012933a4 | email | jeremy.aldea@consultores.wom.cl | channel | MIWOM   | itemCode | 001.004.0003  | itemName | WOM STB pn | itemType | HardwareOP   | type | Postpaid       | serviceType | PRODUCT  |          |          | version | Fibra3      | noOfInstallments | 3      |
      | orderIdDOM | 9YSD9KV88WV7H   | cardId | 617094119c321f00012933a4 | email | jeremy.aldea@consultores.wom.cl | channel | MIWOM   | itemCode | 001.004.0003  | itemName | WOM STB pn | itemType | HardwareOP   | type | Postpaid       | serviceType | PRODUCT  | quantity | null     | version | Fibra3      | noOfInstallments | 3      |
      | orderIdDOM | 9YSD9KV88WV7H   | cardId | 617094119c321f00012933a4 | email | jeremy.aldea@consultores.wom.cl | channel | MIWOM   | itemCode | 001.004.0003  | itemName | WOM STB pn | itemType | HardwareOP   | type | Postpaid       | serviceType | PRODUCT  | quantity | 1asd     | version |             | noOfInstallments | 3      |
      | orderIdDOM | 9YSD9KV88WV7H   | cardId | 617094119c321f00012933a4 | email | jeremy.aldea@consultores.wom.cl | channel | MIWOM   | itemCode | 001.004.0003  | itemName | WOM STB pn | itemType | HardwareOP   | type | Postpaid       | serviceType | PRODUCT  | quantity | 1        | version | Fibasdasd3  | noOfInstallments | 3      |
      | orderIdDOM | 9YSD9KV88WV7H   | cardId | 617094119c321f00012933a4 | email | jeremy.aldea@consultores.wom.cl | channel | MIWOM   | itemCode | 001.004.0003  | itemName | WOM STB pn | itemType | HardwareOP   | type | Postpaid       | serviceType | PRODUCT  | quantity | 1        |         |             | noOfInstallments | 3      |
      | orderIdDOM | 9YSD9KV88WV7H   | cardId | 617094119c321f00012933a4 | email | jeremy.aldea@consultores.wom.cl | channel | MIWOM   | itemCode | 001.004.0003  | itemName | WOM STB pn | itemType | HardwareOP   | type | Postpaid       | serviceType | PRODUCT  | quantity | 1        | version | null        | noOfInstallments | 3      |
      | orderIdDOM | 9YSD9KV88WV7H   | cardId | 617094119c321f00012933a4 | email | jeremy.aldea@consultores.wom.cl | channel | MIWOM   | itemCode | 001.004.0003  | itemName | WOM STB pn | itemType | HardwareOP   | type | Postpaid       | serviceType | PRODUCT  | quantity | 1        | version | Fibra3      | noOfInstallments | a      |
      | orderIdDOM | 9YSD9KV88WV7H   | cardId | 617094119c321f00012933a4 | email | jeremy.aldea@consultores.wom.cl | channel | MIWOM   | itemCode | 001.004.0003  | itemName | WOM STB pn | itemType | HardwareOP   | type | Postpaid       | serviceType | PRODUCT  | quantity | 1        | version | Fibra3      | noOfInstallments | sad3a  |
      | orderIdDOM | 9YSD9KV88WV7H   | cardId | 617094119c321f00012933a4 | email | jeremy.aldea@consultores.wom.cl | channel | MIWOM   | itemCode | 001.004.0003  | itemName | WOM STB pn | itemType | HardwareOP   | type | Postpaid       | serviceType | PRODUCT  | quantity | 1        | version | Fiba3       |                  |        |
      | orderIdDOM | 9YSD9KV88WV7H   | cardId | 617094119c321f00012933a4 | email | jeremy.aldea@consultores.wom.cl | channel | MIWOM   | itemCode | 001.004.0003  | itemName | WOM STB pn | itemType | HardwareOP   | type | Postpaid       | serviceType | PRODUCT  | quantity | 1        | version | Fiba3       | noOfInstallments | null   |


  @ejecucionUnitariasCP
  Scenario Outline: prueba srv40229-1-0 pruebas unitarias (conPromocion)

    Given header 'Content-Type' = 'application/json'
    When url 'http://ott.wom.uat/ocp/customer/srv40229-1-0/rest/productOrdering/productOrderOneShotDelivery'
    And request {"ProductOrderOneShotDeliveryRequestMessage": {"<orderIdDOM>": "<orderId>","<cardId>": "<tarjeta>","<email>": "<e-mail>","<channel>": "<canales>","<items>": [{"<itemCode>": "<codigoItem>","<itemName>": "<nombreP>","<itemType>": "<tipoProducto>","<type>": "<PrePOST>","<serviceType>": "<producto>","<quantity>": <cantidad>,"installmentInfoMsg": {"<version>": "<versionPago>","<noOfInstallments>": <cuotas>},"<promotionDetailMsg>": [{"<promotionID>": "<promocion>","<promotionName>": "<nombrePromocion>"}]}]}}
    And method POST
    And assert responseStatus == 400 || responseStatus == 401 || responseStatus == 402 || responseStatus == 404 || responseStatus == 409 || responseStatus == 501

    Examples:
      | orderIdDOM | orderId      | cardId | tarjeta                  | email | e-mail                          | channel | canales | itemCode | codigoItem   | itemName | nombreP    | itemType | tipoProducto | type | PrePOST  | serviceType | producto | quantity | cantidad | version | versionPago | noOfInstallments | cuotas | promotionID | promocion   | promotionName | nombrePromocion |
      | orderIdDOM | 9YSD9KV88WV7H | cardId | 617094119c321f00012933a4 | email | jeremy.aldea@consultores.wom.cl | channel | MIWOM   | itemCode | 001.004.0003 | itemName | WOM STB pn | itemType | HardwareOP   | type | Postpaid | serviceType | PRODUCT  | quantity | 1        | version | Fibra3      | noOfInstallments | 3      | promotionID |             | promotionName | STB9600         |
      | orderIdDOM | 9YSD9KV88WV7H | cardId | 617094119c321f00012933a4 | email | jeremy.aldea@consultores.wom.cl | channel | MIWOM   | itemCode | 001.004.0003 | itemName | WOM STB pn | itemType | HardwareOP   | type | Postpaid | serviceType | PRODUCT  | quantity | 1        | version | Fibra3      | noOfInstallments | 3      | promotionID | SsasdTB9600 | promotionName | STB9600         |
      | orderIdDOM | 9YSD9KV88WV7H | cardId | 617094119c321f00012933a4 | email | jeremy.aldea@consultores.wom.cl | channel | MIWOM   | itemCode | 001.004.0003 | itemName | WOM STB pn | itemType | HardwareOP   | type | Postpaid | serviceType | PRODUCT  | quantity | 1        | version | Fibra3      | noOfInstallments | 3      |             |             | promotionName | STB9600         |
      | orderIdDOM | 9YSD9KV88WV7H | cardId | 617094119c321f00012933a4 | email | jeremy.aldea@consultores.wom.cl | channel | MIWOM   | itemCode | 001.004.0003 | itemName | WOM STB pn | itemType | HardwareOP   | type | Postpaid | serviceType | PRODUCT  | quantity | 1        | version | Fibra3      | noOfInstallments | 3      | promotionID | null        | promotionName | STB9600         |